### ISSUE TITLE
Minor fix for current ffprobe

### ISSUE THREAD

**Issue by clort81** [CrypticSignal/bitrate-plotter#2]
in ffprobe_out_parser.py i had to change the parser for ffprobe output.

```
    for line in io.TextIOWrapper(process.stdout, encoding="utf-8"):
        ## ffprobe will return the time in ms and the size in bytes.
        if line.strip():  # Check if the line is not empty                                                                                                                       
            dts_time, packet_size = line.strip().split(",", 2)[:2]   # grab only 2 fields
             # original bad code dts_time, packet_size = line.strip().split(",")
```
It was choking on empty lines and for some reason ffprobe was returning lines with a trailing comma.  This gets past that problem.

Thanks for the real hepful tool!

**Comment by CrypticSignal** [comment]
Feel free to open a pull request and you can be listed as a contributor of this tool :)

**Comment by CrypticSignal** [comment]
@clort81 Fixed in commit https://github.com/CrypticSignal/bitrate-plotter/commit/e43c0395db2cb7ef3ab20bcd4bd4bfde22620db4.
